### PR TITLE
Pat and Robbie version clean-up

### LINKED ISSUE #30: Cleanup duplicate scripts
Remove any old test or otherwise depreciated versions of covid_19/robbie and patient_assistant/pat scripts

### PR DESCRIPTION
**Pull request by NeonAndrii**
Resolves #30

### CODE REVIEW

**Comment by NeonAndrii** [comment]
@NeonDaniel is it weird that

**Comment by NeonAndrii** [comment]
@NeonDaniel is it weird that this PR shows commits that are already in the target dev branch?

**Comment by NeonDaniel** [comment]
From your local copy (in PyCharm), try `git rebase origin/dev`. Assuming `origin` refers to `NeonGeckoCom/neon-scripts`.

If everything is up-to-date, you might see the duplicate commits listed when you push to your branch, but the PR to the `NeonGeckoCom/dev` branch will only have the new commits

**Comment by NeonDaniel** [comment]
Superceded by #32

**Pull request closed without merging**
